# Generated by Django 4.1.7 on 2023-04-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador_Principal', '0004_alter_ruta_chofer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'parada', 'verbose_name_plural': 'paradas'},
        ),
        migrations.RemoveField(
            model_name='parada',
            name='ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Controlador_Principal.parada'),
        ),
    ]
