# Generated by Django 4.1.7 on 2023-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador_Principal', '0005_alter_parada_options_alter_ruta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='paradas',
        ),
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.ManyToManyField(to='Controlador_Principal.parada'),
        ),
    ]
