# Generated by Django 4.1.7 on 2023-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador_Principal', '0006_remove_ruta_paradas_ruta_paradas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parada',
            options={'verbose_name': 'parada', 'verbose_name_plural': 'paradas'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'ruta', 'verbose_name_plural': 'rutas'},
        ),
        migrations.AlterField(
            model_name='solicitud_de_combustible',
            name='fecha_de_entrega',
            field=models.DateField(verbose_name='fecha de entrega'),
        ),
    ]
